### ISSUE TITLE
header responsiveness in bigger screens

### ISSUE THREAD

**Issue by anaspxr** [iambasilp/team-estate#3]
As the screen width increases, the logo, menu bar, and account details start moving towards the center, causing a misalignment.
logo is expected to be at left most side and others should be at right most side and should maintain that position at all screen sizes..

![Screenshot 2024-01-20 205700](https://github.com/iambasilp/team-estate/assets/128923778/be7a9e55-6cd9-46fd-b74e-3c70b3bb4713)

**Comment by iambasilp** [comment]
Issue fixed : header responsiveness in bigger screens
![issue](https://github.com/iambasilp/team-estate/assets/73985514/808d4071-6887-4ed9-9d20-d2c8c01ad5fb)
